CREATE TABLE IF NOT EXISTS passages (
    id TEXT PRIMARY KEY,
    passage TEXT NOT NULL,
    references_mythic_era BOOLEAN,
    expresses_scepticism BOOLEAN
);

CREATE TABLE IF NOT EXISTS content_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS noun_extraction_status (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    is_processed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS translations (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    greek_text TEXT NOT NULL,
    english_translation TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS proper_nouns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    exact_form TEXT NOT NULL,
    reference_form TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    UNIQUE(passage_id, exact_form)
);

CREATE TABLE IF NOT EXISTS noun_centrality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    component_id INTEGER NOT NULL,
    degree_centrality DOUBLE PRECISION,
    betweenness_centrality DOUBLE PRECISION,
    eigenvector_centrality DOUBLE PRECISION,
    pagerank DOUBLE PRECISION,
    clustering_coefficient DOUBLE PRECISION,
    timestamp TEXT NOT NULL,
    UNIQUE(reference_form, entity_type, component_id)
);

CREATE TABLE IF NOT EXISTS manual_stopwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS manual_skepticism_stopwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS greek_sentences (
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    sentence_number INTEGER NOT NULL,
    sentence TEXT NOT NULL,
    english_sentence TEXT NOT NULL,
    references_mythic_era BOOLEAN,
    expresses_scepticism BOOLEAN,
    PRIMARY KEY (passage_id, sentence_number)
);

CREATE TABLE IF NOT EXISTS sentence_tagging_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    mode TEXT NOT NULL,
    model TEXT NOT NULL,
    comparison_model TEXT,
    judge_model TEXT,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    token_budget INTEGER,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    discrepancy_count INTEGER NOT NULL DEFAULT 0,
    api_mode TEXT NOT NULL DEFAULT 'direct',
    request_count INTEGER NOT NULL DEFAULT 0,
    openai_batch_id TEXT,
    openai_input_file_id TEXT,
    openai_output_file_id TEXT,
    openai_error_file_id TEXT,
    submitted_at TEXT,
    retrieved_at TEXT,
    notes TEXT
);

ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS api_mode TEXT NOT NULL DEFAULT 'direct';
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS request_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_batch_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_input_file_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_output_file_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_error_file_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS submitted_at TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS retrieved_at TEXT;

CREATE TABLE IF NOT EXISTS sentence_tagging_model_comparisons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    greek_sentence TEXT NOT NULL,
    english_sentence TEXT NOT NULL,
    baseline_model TEXT NOT NULL,
    baseline_references_mythic_era BOOLEAN NOT NULL,
    baseline_expresses_scepticism BOOLEAN NOT NULL,
    comparison_model TEXT NOT NULL,
    comparison_references_mythic_era BOOLEAN,
    comparison_expresses_scepticism BOOLEAN,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    disagrees BOOLEAN NOT NULL DEFAULT FALSE,
    judge_model TEXT,
    judge_winner TEXT,
    judge_reason TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(run_id, passage_id, sentence_number)
);

CREATE TABLE IF NOT EXISTS sentence_greta_tags (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    myth_history_bucket TEXT NOT NULL CHECK (
        myth_history_bucket IN ('mythic', 'historical', 'other')
    ),
    expresses_scepticism BOOLEAN NOT NULL,
    confidence TEXT NOT NULL,
    rationale TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version)
);

CREATE TABLE IF NOT EXISTS sentence_greta_both_tags (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    references_mythic BOOLEAN NOT NULL,
    references_historical BOOLEAN NOT NULL,
    myth_history_bucket TEXT NOT NULL CHECK (
        myth_history_bucket IN ('mythic', 'historical', 'both', 'other')
    ),
    confidence TEXT NOT NULL,
    rationale TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version),
    CHECK (
        (myth_history_bucket = 'both' AND references_mythic AND references_historical)
        OR (myth_history_bucket = 'mythic' AND references_mythic AND NOT references_historical)
        OR (myth_history_bucket = 'historical' AND references_historical AND NOT references_mythic)
        OR (myth_history_bucket = 'other' AND NOT references_mythic AND NOT references_historical)
    ),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_greta_both_tags_bucket
    ON sentence_greta_both_tags (prompt_version, myth_history_bucket);

CREATE TABLE IF NOT EXISTS sentence_greta_both_context_tags (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    references_mythic BOOLEAN NOT NULL,
    references_historical BOOLEAN NOT NULL,
    myth_history_bucket TEXT NOT NULL CHECK (
        myth_history_bucket IN ('mythic', 'historical', 'both', 'other')
    ),
    confidence TEXT NOT NULL,
    rationale TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version),
    CHECK (
        (myth_history_bucket = 'both' AND references_mythic AND references_historical)
        OR (myth_history_bucket = 'mythic' AND references_mythic AND NOT references_historical)
        OR (myth_history_bucket = 'historical' AND references_historical AND NOT references_mythic)
        OR (myth_history_bucket = 'other' AND NOT references_mythic AND NOT references_historical)
    ),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_greta_both_context_tags_bucket
    ON sentence_greta_both_context_tags (prompt_version, myth_history_bucket);

CREATE TABLE IF NOT EXISTS sentence_manual_tags (
    source_id TEXT NOT NULL,
    annotators TEXT NOT NULL,
    source_document TEXT NOT NULL,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    manual_label TEXT NOT NULL,
    manual_bucket TEXT NOT NULL CHECK (
        manual_bucket IN ('mythic', 'historical', 'other', 'mixed_mythic_historical')
    ),
    yellow_mythic BOOLEAN NOT NULL DEFAULT FALSE,
    blue_historical BOOLEAN NOT NULL DEFAULT FALSE,
    green_both BOOLEAN NOT NULL DEFAULT FALSE,
    manual_highlighted_text TEXT NOT NULL DEFAULT '',
    yellow_mythic_letter_count INTEGER NOT NULL DEFAULT 0,
    blue_historical_letter_count INTEGER NOT NULL DEFAULT 0,
    green_both_letter_count INTEGER NOT NULL DEFAULT 0,
    sentence_letter_count INTEGER NOT NULL DEFAULT 0,
    highlighted_letter_fraction DOUBLE PRECISION NOT NULL DEFAULT 0,
    alignment_coverage DOUBLE PRECISION NOT NULL DEFAULT 0,
    alignment_status TEXT NOT NULL DEFAULT '',
    imported_at TEXT NOT NULL,
    PRIMARY KEY (source_id, passage_id, sentence_number),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_manual_tags_bucket
    ON sentence_manual_tags (source_id, manual_bucket);

CREATE TABLE IF NOT EXISTS sentence_tagging_batch_items (
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id)
        ON DELETE CASCADE,
    request_number INTEGER NOT NULL,
    mode TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    estimated_tokens INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'submitted',
    error TEXT,
    created_at TEXT NOT NULL,
    PRIMARY KEY (run_id, request_number),
    UNIQUE (run_id, passage_id, sentence_number),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_tagging_batch_items_pending
    ON sentence_tagging_batch_items (mode, prompt_version, passage_id, sentence_number);

CREATE TABLE IF NOT EXISTS sentence_lemmatization_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    token_budget INTEGER,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS sentence_lemmatizations (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_lemmatization_runs(run_id)
        ON DELETE CASCADE,
    greek_sentence TEXT NOT NULL,
    token_count INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sentence_lemma_tokens (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    token_index INTEGER NOT NULL,
    surface_form TEXT NOT NULL,
    lemma TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version, token_index),
    FOREIGN KEY (passage_id, sentence_number, prompt_version)
        REFERENCES sentence_lemmatizations(passage_id, sentence_number, prompt_version)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_lemma_tokens_lemma
    ON sentence_lemma_tokens (lemma);

CREATE TABLE IF NOT EXISTS word_lemmatization_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    source_scope TEXT NOT NULL,
    batch_size INTEGER NOT NULL,
    surface_form_count INTEGER NOT NULL DEFAULT 0,
    occurrence_count INTEGER NOT NULL DEFAULT 0,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    api_mode TEXT NOT NULL DEFAULT 'direct',
    request_count INTEGER NOT NULL DEFAULT 0,
    openai_batch_id TEXT,
    openai_input_file_id TEXT,
    openai_output_file_id TEXT,
    openai_error_file_id TEXT,
    submitted_at TEXT,
    retrieved_at TEXT,
    notes TEXT
);

ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS api_mode TEXT NOT NULL DEFAULT 'direct';
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS request_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_batch_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_input_file_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_output_file_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_error_file_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS submitted_at TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS retrieved_at TEXT;

CREATE TABLE IF NOT EXISTS word_lemmatization_batches (
    run_id TEXT NOT NULL REFERENCES word_lemmatization_runs(run_id)
        ON DELETE CASCADE,
    batch_number INTEGER NOT NULL,
    item_count INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (run_id, batch_number)
);

CREATE TABLE IF NOT EXISTS word_lemmatization_batch_items (
    run_id TEXT NOT NULL,
    batch_number INTEGER NOT NULL,
    word_index INTEGER NOT NULL,
    surface_form TEXT NOT NULL,
    example_form TEXT NOT NULL,
    occurrence_count INTEGER NOT NULL,
    PRIMARY KEY (run_id, batch_number, word_index),
    FOREIGN KEY (run_id, batch_number)
        REFERENCES word_lemmatization_batches(run_id, batch_number)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS greek_word_lemmas (
    surface_form TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES word_lemmatization_runs(run_id)
        ON DELETE CASCADE,
    example_form TEXT NOT NULL,
    occurrence_count INTEGER NOT NULL,
    lemma TEXT NOT NULL,
    confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
    is_ambiguous BOOLEAN NOT NULL DEFAULT FALSE,
    alternatives TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    created_at TEXT NOT NULL,
    PRIMARY KEY (surface_form, prompt_version)
);

CREATE INDEX IF NOT EXISTS idx_greek_word_lemmas_lemma
    ON greek_word_lemmas (lemma);

CREATE TABLE IF NOT EXISTS phrase_translations (
    phrase TEXT PRIMARY KEY,
    english_translation TEXT NOT NULL,
    is_proper_noun BOOLEAN DEFAULT FALSE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS wikidata_entities (
    wikidata_qid TEXT PRIMARY KEY,
    label TEXT,
    description TEXT,
    entity_type TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    pleiades_id TEXT,
    fetched_at TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wikidata_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    wikidata_qid TEXT REFERENCES wikidata_entities(wikidata_qid) ON UPDATE CASCADE,
    confidence TEXT NOT NULL,
    linked_at TEXT NOT NULL,
    UNIQUE(reference_form, entity_type)
);

CREATE TABLE IF NOT EXISTS proper_noun_spelling_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    wikidata_qid TEXT REFERENCES wikidata_entities(wikidata_qid) ON UPDATE CASCADE,
    preferred_english TEXT NOT NULL,
    allowed_variants TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    deprecated_variants TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    status TEXT NOT NULL DEFAULT 'active',
    notes TEXT,
    updated_at TEXT NOT NULL,
    UNIQUE(reference_form, entity_type)
);

CREATE TABLE IF NOT EXISTS proper_noun_spelling_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id TEXT NOT NULL,
    scan_started_at TEXT NOT NULL,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    source_table TEXT NOT NULL DEFAULT 'translations',
    source_column TEXT NOT NULL DEFAULT 'english_translation',
    source_key TEXT NOT NULL DEFAULT '',
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    wikidata_qid TEXT,
    preferred_english TEXT NOT NULL,
    observed_variant TEXT NOT NULL,
    finding_type TEXT NOT NULL,
    snippet TEXT NOT NULL,
    replacement_applied BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_after_scan BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_summaries (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    model TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    input_tokens INTEGER,
    output_tokens INTEGER
);

CREATE TABLE IF NOT EXISTS mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);
