CREATE TABLE IF NOT EXISTS passages (
    id TEXT PRIMARY KEY,
    passage TEXT NOT NULL,
    references_mythic_era BOOLEAN,
    expresses_scepticism BOOLEAN
);

CREATE TABLE IF NOT EXISTS content_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS noun_extraction_status (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    is_processed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS translations (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    greek_text TEXT NOT NULL,
    english_translation TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS proper_nouns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    exact_form TEXT NOT NULL,
    reference_form TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    UNIQUE(passage_id, exact_form)
);

CREATE TABLE IF NOT EXISTS noun_centrality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    component_id INTEGER NOT NULL,
    degree_centrality DOUBLE PRECISION,
    betweenness_centrality DOUBLE PRECISION,
    eigenvector_centrality DOUBLE PRECISION,
    pagerank DOUBLE PRECISION,
    clustering_coefficient DOUBLE PRECISION,
    timestamp TEXT NOT NULL,
    UNIQUE(reference_form, entity_type, component_id)
);

CREATE TABLE IF NOT EXISTS manual_stopwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS manual_skepticism_stopwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS greek_sentences (
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    sentence_number INTEGER NOT NULL,
    sentence TEXT NOT NULL,
    english_sentence TEXT NOT NULL,
    references_mythic_era BOOLEAN,
    expresses_scepticism BOOLEAN,
    PRIMARY KEY (passage_id, sentence_number)
);

CREATE TABLE IF NOT EXISTS sentence_tagging_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    mode TEXT NOT NULL,
    model TEXT NOT NULL,
    comparison_model TEXT,
    judge_model TEXT,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    token_budget INTEGER,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    discrepancy_count INTEGER NOT NULL DEFAULT 0,
    api_mode TEXT NOT NULL DEFAULT 'direct',
    request_count INTEGER NOT NULL DEFAULT 0,
    openai_batch_id TEXT,
    openai_input_file_id TEXT,
    openai_output_file_id TEXT,
    openai_error_file_id TEXT,
    submitted_at TEXT,
    retrieved_at TEXT,
    notes TEXT
);

ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS api_mode TEXT NOT NULL DEFAULT 'direct';
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS request_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_batch_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_input_file_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_output_file_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS openai_error_file_id TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS submitted_at TEXT;
ALTER TABLE sentence_tagging_runs
    ADD COLUMN IF NOT EXISTS retrieved_at TEXT;

CREATE TABLE IF NOT EXISTS sentence_tagging_model_comparisons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    greek_sentence TEXT NOT NULL,
    english_sentence TEXT NOT NULL,
    baseline_model TEXT NOT NULL,
    baseline_references_mythic_era BOOLEAN NOT NULL,
    baseline_expresses_scepticism BOOLEAN NOT NULL,
    comparison_model TEXT NOT NULL,
    comparison_references_mythic_era BOOLEAN,
    comparison_expresses_scepticism BOOLEAN,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    disagrees BOOLEAN NOT NULL DEFAULT FALSE,
    judge_model TEXT,
    judge_winner TEXT,
    judge_reason TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(run_id, passage_id, sentence_number)
);

CREATE TABLE IF NOT EXISTS sentence_greta_tags (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    myth_history_bucket TEXT NOT NULL CHECK (
        myth_history_bucket IN ('mythic', 'historical', 'other')
    ),
    expresses_scepticism BOOLEAN NOT NULL,
    confidence TEXT NOT NULL,
    rationale TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version)
);

CREATE TABLE IF NOT EXISTS sentence_greta_both_tags (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    references_mythic BOOLEAN NOT NULL,
    references_historical BOOLEAN NOT NULL,
    myth_history_bucket TEXT NOT NULL CHECK (
        myth_history_bucket IN ('mythic', 'historical', 'both', 'other')
    ),
    confidence TEXT NOT NULL,
    rationale TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version),
    CHECK (
        (myth_history_bucket = 'both' AND references_mythic AND references_historical)
        OR (myth_history_bucket = 'mythic' AND references_mythic AND NOT references_historical)
        OR (myth_history_bucket = 'historical' AND references_historical AND NOT references_mythic)
        OR (myth_history_bucket = 'other' AND NOT references_mythic AND NOT references_historical)
    ),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_greta_both_tags_bucket
    ON sentence_greta_both_tags (prompt_version, myth_history_bucket);

CREATE TABLE IF NOT EXISTS sentence_manual_tags (
    source_id TEXT NOT NULL,
    annotators TEXT NOT NULL,
    source_document TEXT NOT NULL,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    manual_label TEXT NOT NULL,
    manual_bucket TEXT NOT NULL CHECK (
        manual_bucket IN ('mythic', 'historical', 'other', 'mixed_mythic_historical')
    ),
    yellow_mythic BOOLEAN NOT NULL DEFAULT FALSE,
    blue_historical BOOLEAN NOT NULL DEFAULT FALSE,
    green_both BOOLEAN NOT NULL DEFAULT FALSE,
    manual_highlighted_text TEXT NOT NULL DEFAULT '',
    yellow_mythic_letter_count INTEGER NOT NULL DEFAULT 0,
    blue_historical_letter_count INTEGER NOT NULL DEFAULT 0,
    green_both_letter_count INTEGER NOT NULL DEFAULT 0,
    sentence_letter_count INTEGER NOT NULL DEFAULT 0,
    highlighted_letter_fraction DOUBLE PRECISION NOT NULL DEFAULT 0,
    alignment_coverage DOUBLE PRECISION NOT NULL DEFAULT 0,
    alignment_status TEXT NOT NULL DEFAULT '',
    imported_at TEXT NOT NULL,
    PRIMARY KEY (source_id, passage_id, sentence_number),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_manual_tags_bucket
    ON sentence_manual_tags (source_id, manual_bucket);

CREATE TABLE IF NOT EXISTS sentence_tagging_batch_items (
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id)
        ON DELETE CASCADE,
    request_number INTEGER NOT NULL,
    mode TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    estimated_tokens INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'submitted',
    error TEXT,
    created_at TEXT NOT NULL,
    PRIMARY KEY (run_id, request_number),
    UNIQUE (run_id, passage_id, sentence_number),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_tagging_batch_items_pending
    ON sentence_tagging_batch_items (mode, prompt_version, passage_id, sentence_number);

CREATE TABLE IF NOT EXISTS sentence_discourse_mode_tags (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    discourse_mode TEXT NOT NULL CHECK (
        discourse_mode IN (
            'route_locative_description',
            'monument_catalogue',
            'historical_narrative',
            'mythological_narrative',
            'ritual_ethnographic_description',
            'sources_traditions_discussion'
        )
    ),
    confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
    rationale TEXT NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_discourse_mode_tags_mode
    ON sentence_discourse_mode_tags (prompt_version, discourse_mode);

CREATE TABLE IF NOT EXISTS sentence_place_state_reviews (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    has_place_state_claim BOOLEAN NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_place_state_reviews_claims
    ON sentence_place_state_reviews (prompt_version, has_place_state_claim);

CREATE TABLE IF NOT EXISTS place_state_mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    claim_index INTEGER NOT NULL,
    exact_place_text TEXT NOT NULL,
    canonical_place_name TEXT NOT NULL,
    place_status TEXT NOT NULL CHECK (
        place_status IN (
            'inhabited_still_exists',
            'extant_uninhabited',
            'ruined_or_remains',
            'abandoned_or_deserted',
            'destroyed_no_trace',
            'renamed_refounded_or_transferred',
            'unclear'
        )
    ),
    temporal_scope TEXT NOT NULL CHECK (
        temporal_scope IN (
            'pausanias_present',
            'past_before_pausanias',
            'mythic_past',
            'later_commentary',
            'unclear'
        )
    ),
    evidence_quote TEXT NOT NULL,
    confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
    rationale TEXT NOT NULL,
    target_label TEXT CHECK (
        target_label IN (
            'survives',
            'does_not_survive',
            'exclude'
        )
    ),
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_tagging_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    UNIQUE (passage_id, sentence_number, prompt_version, claim_index),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_place_state_mentions_status
    ON place_state_mentions (prompt_version, place_status);
CREATE INDEX IF NOT EXISTS idx_place_state_mentions_canonical
    ON place_state_mentions (canonical_place_name);

CREATE TABLE IF NOT EXISTS place_state_candidate_sentences (
    candidate_key TEXT PRIMARY KEY,
    source_version TEXT NOT NULL,
    source_type TEXT NOT NULL CHECK (
        source_type IN (
            'regex_english',
            'regex_greek',
            'recovered_sentence_llm'
        )
    ),
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    category TEXT NOT NULL,
    matched_text TEXT NOT NULL,
    target_label_hint TEXT NOT NULL CHECK (
        target_label_hint IN (
            'survives',
            'does_not_survive',
            'exclude',
            'needs_review'
        )
    ),
    created_at TEXT NOT NULL,
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_place_state_candidate_sentences_passage
    ON place_state_candidate_sentences (source_version, passage_id, sentence_number);
CREATE INDEX IF NOT EXISTS idx_place_state_candidate_sentences_hint
    ON place_state_candidate_sentences (source_version, target_label_hint);

CREATE TABLE IF NOT EXISTS passage_place_state_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    token_budget INTEGER,
    tokens_per_passage_estimate INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    api_mode TEXT NOT NULL DEFAULT 'batch',
    request_count INTEGER NOT NULL DEFAULT 0,
    openai_batch_id TEXT,
    openai_input_file_id TEXT,
    openai_output_file_id TEXT,
    openai_error_file_id TEXT,
    submitted_at TEXT,
    retrieved_at TEXT,
    random_seed TEXT,
    candidate_source_version TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS passage_place_state_batch_items (
    run_id TEXT NOT NULL REFERENCES passage_place_state_runs(run_id)
        ON DELETE CASCADE,
    request_number INTEGER NOT NULL,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    estimated_tokens INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'submitted',
    error TEXT,
    created_at TEXT NOT NULL,
    PRIMARY KEY (run_id, request_number),
    UNIQUE (run_id, passage_id)
);

CREATE INDEX IF NOT EXISTS idx_passage_place_state_batch_items_pending
    ON passage_place_state_batch_items (passage_id, status);

CREATE TABLE IF NOT EXISTS passage_place_state_reviews (
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    has_place_state_claim BOOLEAN NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES passage_place_state_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, prompt_version)
);

CREATE INDEX IF NOT EXISTS idx_passage_place_state_reviews_claims
    ON passage_place_state_reviews (prompt_version, has_place_state_claim);

CREATE TABLE IF NOT EXISTS passage_place_state_mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    claim_index INTEGER NOT NULL,
    sentence_number INTEGER,
    exact_place_text TEXT NOT NULL,
    canonical_place_name TEXT NOT NULL,
    place_status TEXT NOT NULL CHECK (
        place_status IN (
            'inhabited_still_exists',
            'extant_uninhabited',
            'ruined_or_remains',
            'abandoned_or_deserted',
            'destroyed_no_trace',
            'renamed_refounded_or_transferred',
            'unclear'
        )
    ),
    temporal_scope TEXT NOT NULL CHECK (
        temporal_scope IN (
            'pausanias_present',
            'past_before_pausanias',
            'mythic_past',
            'later_commentary',
            'unclear'
        )
    ),
    evidence_quote TEXT NOT NULL,
    confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
    rationale TEXT NOT NULL,
    target_label TEXT CHECK (
        target_label IN (
            'survives',
            'does_not_survive',
            'exclude'
        )
    ),
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    run_id TEXT NOT NULL REFERENCES passage_place_state_runs(run_id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    UNIQUE (passage_id, prompt_version, claim_index),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_passage_place_state_mentions_status
    ON passage_place_state_mentions (prompt_version, place_status);
CREATE INDEX IF NOT EXISTS idx_passage_place_state_mentions_canonical
    ON passage_place_state_mentions (canonical_place_name);

CREATE TABLE IF NOT EXISTS section_people_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    token_budget INTEGER,
    tokens_per_section_estimate INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    api_mode TEXT NOT NULL DEFAULT 'batch',
    request_count INTEGER NOT NULL DEFAULT 0,
    openai_batch_id TEXT,
    openai_input_file_id TEXT,
    openai_output_file_id TEXT,
    openai_error_file_id TEXT,
    submitted_at TEXT,
    retrieved_at TEXT,
    random_seed TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS section_people_batch_items (
    run_id TEXT NOT NULL REFERENCES section_people_runs(run_id)
        ON DELETE CASCADE,
    request_number INTEGER NOT NULL,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    estimated_tokens INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'submitted',
    error TEXT,
    created_at TEXT NOT NULL,
    PRIMARY KEY (run_id, request_number),
    UNIQUE (run_id, passage_id)
);

CREATE INDEX IF NOT EXISTS idx_section_people_batch_items_pending
    ON section_people_batch_items (passage_id, status);

CREATE TABLE IF NOT EXISTS section_people_mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES section_people_runs(run_id) ON DELETE CASCADE,
    mention_order INTEGER NOT NULL,
    mention_text TEXT NOT NULL,
    canonical_name TEXT NOT NULL DEFAULT '',
    is_named BOOLEAN NOT NULL,
    gender TEXT NOT NULL CHECK (gender IN ('male', 'female', 'unknown')),
    person_category TEXT NOT NULL CHECK (
        person_category IN (
            'human', 'hero', 'deity', 'mythic_person', 'collective', 'uncertain'
        )
    ),
    count_kind TEXT NOT NULL CHECK (
        count_kind IN ('individual', 'group_exact', 'group_uncounted')
    ),
    person_count INTEGER NOT NULL DEFAULT 1 CHECK (person_count >= 0),
    confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
    rationale TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    UNIQUE (passage_id, sentence_number, prompt_version, mention_order),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_section_people_mentions_class
    ON section_people_mentions (prompt_version, is_named, gender);

CREATE INDEX IF NOT EXISTS idx_section_people_mentions_sentence
    ON section_people_mentions (passage_id, sentence_number, prompt_version);

CREATE TABLE IF NOT EXISTS sentence_lemmatization_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    token_budget INTEGER,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS sentence_lemmatizations (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_lemmatization_runs(run_id)
        ON DELETE CASCADE,
    greek_sentence TEXT NOT NULL,
    token_count INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sentence_lemma_tokens (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    token_index INTEGER NOT NULL,
    surface_form TEXT NOT NULL,
    lemma TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, prompt_version, token_index),
    FOREIGN KEY (passage_id, sentence_number, prompt_version)
        REFERENCES sentence_lemmatizations(passage_id, sentence_number, prompt_version)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_lemma_tokens_lemma
    ON sentence_lemma_tokens (lemma);

CREATE TABLE IF NOT EXISTS sentence_udpipe_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model_name TEXT NOT NULL,
    model_path TEXT NOT NULL,
    model_sha256 TEXT NOT NULL,
    udpipe_version TEXT NOT NULL,
    input_format TEXT NOT NULL DEFAULT 'horizontal',
    status TEXT NOT NULL,
    processed_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT
);

ALTER TABLE sentence_udpipe_runs
    ALTER COLUMN input_format SET DEFAULT 'horizontal';

CREATE TABLE IF NOT EXISTS sentence_udpipe_analyses (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    model_name TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_udpipe_runs(run_id)
        ON DELETE CASCADE,
    greek_sentence TEXT NOT NULL,
    conllu TEXT NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, model_name),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sentence_udpipe_tokens (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    model_name TEXT NOT NULL,
    token_order INTEGER NOT NULL,
    token_id TEXT NOT NULL,
    form TEXT NOT NULL,
    lemma TEXT,
    upos TEXT,
    xpos TEXT,
    feats_raw TEXT NOT NULL DEFAULT '_',
    head_token_id TEXT,
    deprel TEXT,
    deps_raw TEXT NOT NULL DEFAULT '_',
    misc_raw TEXT NOT NULL DEFAULT '_',
    is_multiword_token BOOLEAN NOT NULL DEFAULT FALSE,
    is_empty_node BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, model_name, token_order),
    FOREIGN KEY (passage_id, sentence_number, model_name)
        REFERENCES sentence_udpipe_analyses(passage_id, sentence_number, model_name)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_udpipe_tokens_lemma
    ON sentence_udpipe_tokens (model_name, lemma);

CREATE INDEX IF NOT EXISTS idx_sentence_udpipe_tokens_upos
    ON sentence_udpipe_tokens (model_name, upos);

CREATE INDEX IF NOT EXISTS idx_sentence_udpipe_tokens_deprel
    ON sentence_udpipe_tokens (model_name, deprel);

CREATE TABLE IF NOT EXISTS sentence_trankit_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model_name TEXT NOT NULL,
    model_path TEXT NOT NULL,
    source_path TEXT NOT NULL,
    model_sha256 TEXT NOT NULL,
    trankit_version TEXT NOT NULL,
    python_version TEXT NOT NULL,
    annotation_scheme TEXT NOT NULL DEFAULT 'AGDT',
    status TEXT NOT NULL,
    processed_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS sentence_trankit_analyses (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    model_name TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_trankit_runs(run_id)
        ON DELETE CASCADE,
    greek_sentence TEXT NOT NULL,
    conllu TEXT NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, model_name),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sentence_trankit_tokens (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    model_name TEXT NOT NULL,
    token_order INTEGER NOT NULL,
    token_id TEXT NOT NULL,
    form TEXT NOT NULL,
    lemma TEXT,
    pos TEXT,
    xpos TEXT,
    feats_raw TEXT NOT NULL DEFAULT '_',
    head_token_id TEXT,
    deprel TEXT,
    deps_raw TEXT NOT NULL DEFAULT '_',
    misc_raw TEXT NOT NULL DEFAULT '_',
    is_multiword_token BOOLEAN NOT NULL DEFAULT FALSE,
    is_empty_node BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, model_name, token_order),
    FOREIGN KEY (passage_id, sentence_number, model_name)
        REFERENCES sentence_trankit_analyses(passage_id, sentence_number, model_name)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_trankit_tokens_lemma
    ON sentence_trankit_tokens (model_name, lemma);

CREATE INDEX IF NOT EXISTS idx_sentence_trankit_tokens_pos
    ON sentence_trankit_tokens (model_name, pos);

CREATE INDEX IF NOT EXISTS idx_sentence_trankit_tokens_deprel
    ON sentence_trankit_tokens (model_name, deprel);

CREATE TABLE IF NOT EXISTS sentence_llm_grammar_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS sentence_llm_grammar_analyses (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES sentence_llm_grammar_runs(run_id)
        ON DELETE CASCADE,
    greek_sentence TEXT NOT NULL,
    conllu TEXT NOT NULL,
    sentence_note TEXT NOT NULL DEFAULT '',
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, model, prompt_version),
    FOREIGN KEY (passage_id, sentence_number)
        REFERENCES greek_sentences(passage_id, sentence_number)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sentence_llm_grammar_tokens (
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    token_order INTEGER NOT NULL,
    token_id TEXT NOT NULL,
    form TEXT NOT NULL,
    lemma TEXT,
    upos TEXT,
    xpos TEXT,
    feats_raw TEXT NOT NULL DEFAULT '_',
    head_token_id TEXT,
    deprel TEXT,
    confidence TEXT NOT NULL DEFAULT 'medium',
    note TEXT NOT NULL DEFAULT '',
    is_multiword_token BOOLEAN NOT NULL DEFAULT FALSE,
    is_empty_node BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (passage_id, sentence_number, model, prompt_version, token_order),
    FOREIGN KEY (passage_id, sentence_number, model, prompt_version)
        REFERENCES sentence_llm_grammar_analyses(
            passage_id, sentence_number, model, prompt_version
        )
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sentence_llm_grammar_tokens_lemma
    ON sentence_llm_grammar_tokens (model, prompt_version, lemma);

CREATE INDEX IF NOT EXISTS idx_sentence_llm_grammar_tokens_upos
    ON sentence_llm_grammar_tokens (model, prompt_version, upos);

CREATE INDEX IF NOT EXISTS idx_sentence_llm_grammar_tokens_deprel
    ON sentence_llm_grammar_tokens (model, prompt_version, deprel);

CREATE TABLE IF NOT EXISTS word_lemmatization_runs (
    run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    status TEXT NOT NULL,
    source_scope TEXT NOT NULL,
    batch_size INTEGER NOT NULL,
    surface_form_count INTEGER NOT NULL DEFAULT 0,
    occurrence_count INTEGER NOT NULL DEFAULT 0,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    api_mode TEXT NOT NULL DEFAULT 'direct',
    request_count INTEGER NOT NULL DEFAULT 0,
    openai_batch_id TEXT,
    openai_input_file_id TEXT,
    openai_output_file_id TEXT,
    openai_error_file_id TEXT,
    submitted_at TEXT,
    retrieved_at TEXT,
    notes TEXT
);

ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS api_mode TEXT NOT NULL DEFAULT 'direct';
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS request_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_batch_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_input_file_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_output_file_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS openai_error_file_id TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS submitted_at TEXT;
ALTER TABLE word_lemmatization_runs
    ADD COLUMN IF NOT EXISTS retrieved_at TEXT;

CREATE TABLE IF NOT EXISTS word_lemmatization_batches (
    run_id TEXT NOT NULL REFERENCES word_lemmatization_runs(run_id)
        ON DELETE CASCADE,
    batch_number INTEGER NOT NULL,
    item_count INTEGER NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (run_id, batch_number)
);

CREATE TABLE IF NOT EXISTS word_lemmatization_batch_items (
    run_id TEXT NOT NULL,
    batch_number INTEGER NOT NULL,
    word_index INTEGER NOT NULL,
    surface_form TEXT NOT NULL,
    example_form TEXT NOT NULL,
    occurrence_count INTEGER NOT NULL,
    PRIMARY KEY (run_id, batch_number, word_index),
    FOREIGN KEY (run_id, batch_number)
        REFERENCES word_lemmatization_batches(run_id, batch_number)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS greek_word_lemmas (
    surface_form TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    model TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES word_lemmatization_runs(run_id)
        ON DELETE CASCADE,
    example_form TEXT NOT NULL,
    occurrence_count INTEGER NOT NULL,
    lemma TEXT NOT NULL,
    confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
    is_ambiguous BOOLEAN NOT NULL DEFAULT FALSE,
    alternatives TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    created_at TEXT NOT NULL,
    PRIMARY KEY (surface_form, prompt_version)
);

CREATE INDEX IF NOT EXISTS idx_greek_word_lemmas_lemma
    ON greek_word_lemmas (lemma);

CREATE TABLE IF NOT EXISTS phrase_translations (
    phrase TEXT PRIMARY KEY,
    english_translation TEXT NOT NULL,
    is_proper_noun BOOLEAN DEFAULT FALSE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS wikidata_entities (
    wikidata_qid TEXT PRIMARY KEY,
    label TEXT,
    description TEXT,
    entity_type TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    pleiades_id TEXT,
    fetched_at TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wikidata_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    wikidata_qid TEXT REFERENCES wikidata_entities(wikidata_qid) ON UPDATE CASCADE,
    confidence TEXT NOT NULL,
    linked_at TEXT NOT NULL,
    UNIQUE(reference_form, entity_type)
);

CREATE TABLE IF NOT EXISTS manto_releases (
    record_id BIGINT PRIMARY KEY,
    concept_record_id BIGINT,
    doi TEXT,
    concept_doi TEXT,
    version TEXT,
    title TEXT,
    zenodo_created_at TEXT,
    zenodo_modified_at TEXT,
    license_id TEXT,
    file_key TEXT NOT NULL,
    file_size BIGINT,
    file_checksum TEXT,
    file_url TEXT NOT NULL,
    local_zip_path TEXT,
    downloaded_at TEXT,
    imported_at TEXT,
    import_status TEXT NOT NULL DEFAULT 'discovered',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS manto_raw_records (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    record_number INTEGER NOT NULL,
    file_format TEXT NOT NULL CHECK (file_format IN ('csv', 'json')),
    record_id TEXT,
    record_kind TEXT,
    label TEXT,
    evidence_source_label TEXT,
    evidence_latest_year INTEGER,
    imported_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, file_path, record_number)
);

CREATE INDEX IF NOT EXISTS idx_manto_raw_records_kind
    ON manto_raw_records (release_record_id, record_kind);
CREATE INDEX IF NOT EXISTS idx_manto_raw_records_record_id
    ON manto_raw_records (release_record_id, record_id);

CREATE TABLE IF NOT EXISTS manto_entities (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    manto_id TEXT NOT NULL,
    entity_kind TEXT NOT NULL,
    label TEXT,
    type_label TEXT,
    evidence_source_label TEXT,
    evidence_latest_year INTEGER,
    imported_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, manto_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_entities_label
    ON manto_entities (release_record_id, label);
CREATE INDEX IF NOT EXISTS idx_manto_entities_kind
    ON manto_entities (release_record_id, entity_kind);

CREATE TABLE IF NOT EXISTS manto_entity_details (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    object_id TEXT NOT NULL,
    nodegoat_id TEXT NOT NULL,
    name TEXT NOT NULL,
    information TEXT NOT NULL DEFAULT '',
    pleiades_id TEXT,
    somewhere_in_or_near_object_id TEXT,
    somewhere_in_or_near_label TEXT,
    topos_text TEXT NOT NULL DEFAULT '',
    commentary TEXT NOT NULL DEFAULT '',
    imported_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, object_id),
    UNIQUE (release_record_id, nodegoat_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_entity_details_name
    ON manto_entity_details (release_record_id, name);
CREATE INDEX IF NOT EXISTS idx_manto_entity_details_pleiades
    ON manto_entity_details (release_record_id, pleiades_id);

CREATE TABLE IF NOT EXISTS manto_tie_details (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    object_id TEXT NOT NULL,
    nodegoat_id TEXT NOT NULL,
    name TEXT NOT NULL,
    imported_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, object_id),
    UNIQUE (release_record_id, nodegoat_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_tie_details_name
    ON manto_tie_details (release_record_id, name);

CREATE TABLE IF NOT EXISTS manto_place_status_labels (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    object_id TEXT NOT NULL,
    nodegoat_id TEXT NOT NULL,
    place_name TEXT NOT NULL,
    information TEXT NOT NULL DEFAULT '',
    label_source_version TEXT NOT NULL,
    target_label TEXT NOT NULL CHECK (
        target_label IN (
            'survives',
            'does_not_survive',
            'exclude'
        )
    ),
    status_reason TEXT NOT NULL,
    matched_phrase TEXT NOT NULL DEFAULT '',
    is_pausanias_mentioned BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, object_id, label_source_version),
    FOREIGN KEY (release_record_id, object_id)
        REFERENCES manto_entity_details(release_record_id, object_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_manto_place_status_labels_target
    ON manto_place_status_labels (release_record_id, label_source_version, target_label);

CREATE TABLE IF NOT EXISTS manto_edges (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    edge_id TEXT NOT NULL,
    source_manto_id TEXT NOT NULL,
    target_manto_id TEXT NOT NULL,
    relation_type TEXT NOT NULL,
    evidence_source_label TEXT,
    evidence_latest_year INTEGER,
    is_pre_pausanias BOOLEAN NOT NULL DEFAULT FALSE,
    excluded_reason TEXT,
    imported_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, edge_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_edges_source
    ON manto_edges (release_record_id, source_manto_id);
CREATE INDEX IF NOT EXISTS idx_manto_edges_target
    ON manto_edges (release_record_id, target_manto_id);
CREATE INDEX IF NOT EXISTS idx_manto_edges_pre_pausanias
    ON manto_edges (release_record_id, is_pre_pausanias);

CREATE TABLE IF NOT EXISTS manto_place_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    wikidata_qid TEXT REFERENCES wikidata_entities(wikidata_qid) ON UPDATE CASCADE,
    pleiades_id TEXT,
    manto_id TEXT NOT NULL,
    manto_label TEXT,
    match_method TEXT NOT NULL,
    confidence TEXT NOT NULL CHECK (
        confidence IN ('high', 'medium', 'low', 'rejected')
    ),
    rationale TEXT NOT NULL DEFAULT '',
    reviewed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (release_record_id, reference_form, entity_type, manto_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_place_links_reference
    ON manto_place_links (release_record_id, reference_form, entity_type);
CREATE INDEX IF NOT EXISTS idx_manto_place_links_manto
    ON manto_place_links (release_record_id, manto_id);

CREATE TABLE IF NOT EXISTS manto_place_network_features (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    feature_set_version TEXT NOT NULL,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    manto_id TEXT NOT NULL,
    manto_label TEXT,
    pre_pausanias_only BOOLEAN NOT NULL,
    degree INTEGER NOT NULL,
    degree_centrality DOUBLE PRECISION NOT NULL,
    pagerank DOUBLE PRECISION NOT NULL,
    betweenness_centrality DOUBLE PRECISION NOT NULL,
    clustering_coefficient DOUBLE PRECISION NOT NULL,
    component_size INTEGER NOT NULL,
    community_size INTEGER NOT NULL,
    high_centrality_neighbor_count INTEGER NOT NULL,
    max_neighbor_pagerank DOUBLE PRECISION NOT NULL,
    shared_neighbor_high_centrality_score DOUBLE PRECISION NOT NULL,
    k_core INTEGER,
    hop_distance_to_large_place INTEGER,
    nodes_within_two_hops INTEGER,
    nodes_within_three_hops INTEGER,
    disjoint_paths_to_large_place INTEGER,
    bridge_edge_fraction DOUBLE PRECISION,
    within_module_degree_zscore DOUBLE PRECISION,
    participation_coefficient DOUBLE PRECISION,
    created_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, feature_set_version, reference_form, entity_type, manto_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_place_network_features_reference
    ON manto_place_network_features (
        release_record_id,
        feature_set_version,
        reference_form,
        entity_type
    );

CREATE TABLE IF NOT EXISTS manto_place_connectedness_features (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    feature_set_version TEXT NOT NULL,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    manto_id TEXT NOT NULL,
    manto_label TEXT,
    pre_pausanias_only BOOLEAN NOT NULL,
    place_graph_degree INTEGER NOT NULL,
    place_graph_pagerank DOUBLE PRECISION NOT NULL,
    local_place_neighbor_count INTEGER NOT NULL,
    direct_place_neighbor_count INTEGER NOT NULL,
    same_parent_place_neighbor_count INTEGER NOT NULL,
    large_place_neighbor_count INTEGER NOT NULL,
    large_place_max_degree INTEGER NOT NULL,
    large_place_max_pagerank DOUBLE PRECISION NOT NULL,
    has_large_place_neighbor BOOLEAN NOT NULL,
    strong_place_tie_count INTEGER NOT NULL,
    mythic_figure_count INTEGER NOT NULL,
    action_pattern_count INTEGER NOT NULL,
    shared_mythic_figure_neighbor_count INTEGER NOT NULL,
    shared_mythic_figure_count INTEGER NOT NULL,
    max_shared_mythic_figures_with_neighbor INTEGER NOT NULL,
    shared_mythic_figure_large_place_neighbor_count INTEGER NOT NULL,
    shared_action_neighbor_count INTEGER NOT NULL,
    shared_action_pattern_count INTEGER NOT NULL,
    shared_action_neighbor_pattern_count INTEGER NOT NULL,
    max_shared_action_patterns_with_neighbor INTEGER NOT NULL,
    shared_action_large_place_neighbor_count INTEGER NOT NULL,
    exclusive_figure_count INTEGER,
    panhellenic_figure_count INTEGER,
    figure_mean_ubiquity DOUBLE PRECISION,
    figure_max_ubiquity INTEGER,
    kin_linked_place_count INTEGER,
    kin_linked_neighbor_count INTEGER,
    kin_linked_large_place_count INTEGER,
    action_profile_entropy DOUBLE PRECISION,
    max_action_cosine_with_neighbor DOUBLE PRECISION,
    mean_action_cosine_with_neighbors DOUBLE PRECISION,
    max_action_cosine_with_large_place DOUBLE PRECISION,
    archaic_story_count INTEGER,
    classical_story_count INTEGER,
    hellenistic_story_count INTEGER,
    early_imperial_story_count INTEGER,
    earliest_attestation_year INTEGER,
    latest_attestation_year INTEGER,
    attestation_span_years INTEGER,
    shared_figure_count_zscore DOUBLE PRECISION,
    shared_figure_neighbor_zscore DOUBLE PRECISION,
    created_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, feature_set_version, reference_form, entity_type, manto_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_place_connectedness_features_reference
    ON manto_place_connectedness_features (
        release_record_id,
        feature_set_version,
        reference_form,
        entity_type
    );

CREATE TABLE IF NOT EXISTS curated_place_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_name TEXT NOT NULL,
    manto_id TEXT NOT NULL DEFAULT '',
    manto_label TEXT,
    source TEXT NOT NULL CHECK (source IN ('manual', 'llm')),
    model TEXT,
    rationale TEXT NOT NULL DEFAULT '',
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    reviewed BOOLEAN NOT NULL DEFAULT FALSE,
    rejected BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (place_name, manto_id)
);

CREATE INDEX IF NOT EXISTS idx_curated_place_links_place
    ON curated_place_links (place_name);

CREATE TABLE IF NOT EXISTS pleiades_places (
    pleiades_id TEXT PRIMARY KEY,
    title TEXT,
    representative_latitude DOUBLE PRECISION,
    representative_longitude DOUBLE PRECISION,
    location_precision TEXT,
    time_periods TEXT,
    imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS manto_place_geography_features (
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    feature_set_version TEXT NOT NULL,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    manto_id TEXT NOT NULL,
    manto_label TEXT,
    pre_pausanias_only BOOLEAN NOT NULL,
    has_coordinates BOOLEAN NOT NULL,
    geo_distance_to_nearest_large_place_km DOUBLE PRECISION NOT NULL,
    geo_distance_to_nearest_place_km DOUBLE PRECISION NOT NULL,
    places_within_50km_count INTEGER NOT NULL,
    narrative_neighbor_count_with_coords INTEGER NOT NULL,
    mean_narrative_neighbor_distance_km DOUBLE PRECISION NOT NULL,
    min_narrative_neighbor_distance_km DOUBLE PRECISION NOT NULL,
    max_narrative_neighbor_distance_km DOUBLE PRECISION NOT NULL,
    neighbors_within_25km_count INTEGER NOT NULL,
    neighbors_within_50km_count INTEGER NOT NULL,
    neighbors_within_100km_count INTEGER NOT NULL,
    local_tie_fraction_50km DOUBLE PRECISION NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (release_record_id, feature_set_version, reference_form, entity_type, manto_id)
);

CREATE INDEX IF NOT EXISTS idx_manto_place_geography_features_reference
    ON manto_place_geography_features (
        release_record_id,
        feature_set_version,
        reference_form,
        entity_type
    );

CREATE TABLE IF NOT EXISTS place_survival_model_runs (
    run_id TEXT PRIMARY KEY,
    release_record_id BIGINT NOT NULL REFERENCES manto_releases(record_id) ON DELETE CASCADE,
    feature_set_version TEXT NOT NULL,
    label_source_version TEXT NOT NULL,
    model_type TEXT NOT NULL,
    pre_pausanias_only BOOLEAN NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    status TEXT NOT NULL,
    sample_count INTEGER NOT NULL DEFAULT 0,
    positive_count INTEGER NOT NULL DEFAULT 0,
    negative_count INTEGER NOT NULL DEFAULT 0,
    accuracy DOUBLE PRECISION,
    baseline_accuracy DOUBLE PRECISION,
    balanced_accuracy DOUBLE PRECISION,
    precision_survives DOUBLE PRECISION,
    recall_survives DOUBLE PRECISION,
    f1_survives DOUBLE PRECISION,
    precision_does_not_survive DOUBLE PRECISION,
    recall_does_not_survive DOUBLE PRECISION,
    f1_does_not_survive DOUBLE PRECISION,
    true_survives_pred_survives INTEGER,
    true_survives_pred_does_not_survive INTEGER,
    true_does_not_survive_pred_survives INTEGER,
    true_does_not_survive_pred_does_not_survive INTEGER,
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS place_survival_feature_scores (
    run_id TEXT NOT NULL REFERENCES place_survival_model_runs(run_id) ON DELETE CASCADE,
    feature_name TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    abs_coefficient DOUBLE PRECISION NOT NULL,
    direction TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (run_id, feature_name)
);

CREATE TABLE IF NOT EXISTS proper_noun_spelling_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    wikidata_qid TEXT REFERENCES wikidata_entities(wikidata_qid) ON UPDATE CASCADE,
    preferred_english TEXT NOT NULL,
    allowed_variants TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    deprecated_variants TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    status TEXT NOT NULL DEFAULT 'active',
    notes TEXT,
    updated_at TEXT NOT NULL,
    UNIQUE(reference_form, entity_type)
);

CREATE TABLE IF NOT EXISTS proper_noun_spelling_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id TEXT NOT NULL,
    scan_started_at TEXT NOT NULL,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    source_table TEXT NOT NULL DEFAULT 'translations',
    source_column TEXT NOT NULL DEFAULT 'english_translation',
    source_key TEXT NOT NULL DEFAULT '',
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    wikidata_qid TEXT,
    preferred_english TEXT NOT NULL,
    observed_variant TEXT NOT NULL,
    finding_type TEXT NOT NULL,
    snippet TEXT NOT NULL,
    replacement_applied BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_after_scan BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_summaries (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    model TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    input_tokens INTEGER,
    output_tokens INTEGER
);

CREATE TABLE IF NOT EXISTS mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS stylometry_chunks (
    chunk_set TEXT NOT NULL,
    chunk_id TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    tokenizer_version TEXT NOT NULL,
    passage_start TEXT NOT NULL,
    passage_end TEXT NOT NULL,
    book_start INTEGER NOT NULL,
    book_end INTEGER NOT NULL,
    token_count INTEGER NOT NULL,
    sentence_count INTEGER NOT NULL,
    is_messenian_wars BOOLEAN NOT NULL,
    overlap_fraction_messenian_wars DOUBLE PRECISION NOT NULL,
    is_book4 BOOLEAN NOT NULL,
    is_book8 BOOLEAN NOT NULL,
    is_control BOOLEAN NOT NULL,
    is_boundary_chunk BOOLEAN NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (chunk_set, chunk_id)
);

CREATE INDEX IF NOT EXISTS idx_stylometry_chunks_flags
    ON stylometry_chunks (chunk_set, is_messenian_wars, is_book4, is_book8);

CREATE TABLE IF NOT EXISTS stylometry_chunk_sentences (
    chunk_set TEXT NOT NULL,
    chunk_id TEXT NOT NULL,
    passage_id TEXT NOT NULL,
    sentence_number INTEGER NOT NULL,
    token_count INTEGER NOT NULL,
    PRIMARY KEY (chunk_set, chunk_id, passage_id, sentence_number),
    FOREIGN KEY (chunk_set, chunk_id)
        REFERENCES stylometry_chunks(chunk_set, chunk_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_stylometry_chunk_sentences_passage
    ON stylometry_chunk_sentences (passage_id, sentence_number);
