CREATE TABLE IF NOT EXISTS passages (
    id TEXT PRIMARY KEY,
    passage TEXT NOT NULL,
    references_mythic_era BOOLEAN,
    expresses_scepticism BOOLEAN
);

CREATE TABLE IF NOT EXISTS content_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS noun_extraction_status (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    is_processed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS translations (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    greek_text TEXT NOT NULL,
    english_translation TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS proper_nouns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    exact_form TEXT NOT NULL,
    reference_form TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    UNIQUE(passage_id, exact_form)
);

CREATE TABLE IF NOT EXISTS noun_centrality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    component_id INTEGER NOT NULL,
    degree_centrality DOUBLE PRECISION,
    betweenness_centrality DOUBLE PRECISION,
    eigenvector_centrality DOUBLE PRECISION,
    pagerank DOUBLE PRECISION,
    clustering_coefficient DOUBLE PRECISION,
    timestamp TEXT NOT NULL,
    UNIQUE(reference_form, entity_type, component_id)
);

CREATE TABLE IF NOT EXISTS manual_stopwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS manual_skepticism_stopwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS greek_sentences (
    passage_id TEXT NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
    sentence_number INTEGER NOT NULL,
    sentence TEXT NOT NULL,
    english_sentence TEXT NOT NULL,
    references_mythic_era BOOLEAN,
    expresses_scepticism BOOLEAN,
    PRIMARY KEY (passage_id, sentence_number)
);

CREATE TABLE IF NOT EXISTS phrase_translations (
    phrase TEXT PRIMARY KEY,
    english_translation TEXT NOT NULL,
    is_proper_noun BOOLEAN DEFAULT FALSE,
    timestamp TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS wikidata_entities (
    wikidata_qid TEXT PRIMARY KEY,
    label TEXT,
    description TEXT,
    entity_type TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    pleiades_id TEXT,
    fetched_at TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wikidata_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_form TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    english_transcription TEXT NOT NULL,
    wikidata_qid TEXT REFERENCES wikidata_entities(wikidata_qid) ON UPDATE CASCADE,
    confidence TEXT NOT NULL,
    linked_at TEXT NOT NULL,
    UNIQUE(reference_form, entity_type)
);

CREATE TABLE IF NOT EXISTS passage_summaries (
    passage_id TEXT PRIMARY KEY REFERENCES passages(id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    model TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    input_tokens INTEGER,
    output_tokens INTEGER
);

CREATE TABLE IF NOT EXISTS mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passage_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS simplified_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_mythicness_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_mythic INTEGER NOT NULL,
    mythic_count INTEGER NOT NULL,
    non_mythic_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_skepticism_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    idf DOUBLE PRECISION NOT NULL,
    point_value DOUBLE PRECISION NOT NULL,
    is_skeptical INTEGER NOT NULL,
    skeptical_count INTEGER NOT NULL,
    non_skeptical_count INTEGER NOT NULL,
    p_value DOUBLE PRECISION NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_mythicness_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sentence_simplified_skepticism_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accuracy DOUBLE PRECISION NOT NULL,
    baseline_accuracy DOUBLE PRECISION NOT NULL,
    baseline_label INTEGER NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    selected_feature_count INTEGER NOT NULL,
    precision_0 DOUBLE PRECISION NOT NULL,
    recall_0 DOUBLE PRECISION NOT NULL,
    f1_0 DOUBLE PRECISION NOT NULL,
    support_0 INTEGER NOT NULL,
    precision_1 DOUBLE PRECISION NOT NULL,
    recall_1 DOUBLE PRECISION NOT NULL,
    f1_1 DOUBLE PRECISION NOT NULL,
    support_1 INTEGER NOT NULL,
    actual_0_pred_0 INTEGER NOT NULL,
    actual_0_pred_1 INTEGER NOT NULL,
    actual_1_pred_0 INTEGER NOT NULL,
    actual_1_pred_1 INTEGER NOT NULL,
    baseline_actual_0_pred_0 INTEGER NOT NULL,
    baseline_actual_0_pred_1 INTEGER NOT NULL,
    baseline_actual_1_pred_0 INTEGER NOT NULL,
    baseline_actual_1_pred_1 INTEGER NOT NULL,
    timestamp TEXT NOT NULL
);
